// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { theme, App } from "antd/es";
import ConfigProvider from "antd/es/config-provider";
import { AuthProvider } from "@/providers/auth-providers";
import { ReviewProvider } from "@/providers/review-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { darkAlgorithm } = theme;

  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#fa541c",
              colorInfo: "#fa541c",
              fontSize: 14,
            },
            components: {
              Input: {
                colorText: "rgb(255,255,255)",
              },
            },
            algorithm: darkAlgorithm,
          }}
        >
          <App>
            <AuthProvider>
              <ReviewProvider>{children}</ReviewProvider>
            </AuthProvider>
          </App>
        </ConfigProvider>
      </body>
    </html>
  );
}
