import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { theme } from "antd/es";
import ConfigProvider from "antd/es/config-provider";
import { AuthProvider } from "@/providers/auth-providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { darkAlgorithm } = theme;
  return (
    <html lang="en">
      <AuthProvider>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#fa541c",
              colorInfo: "#fa541c",
              fontSize: 14,
            },
            components: {
              Input: {
                colorText: "rgb(255,255,255)",
              },
            },
            algorithm: darkAlgorithm,
          }}
        >
          <body>
            {children}
          </body>
        </ConfigProvider>
      </AuthProvider>
    </html>
  );
}
